

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)
df = pd.read_csv('nutrition_facts.csv') 
print("Dataset Head:\n", df.head())
print("\nDataset Info:")
df.info()
print("\nMissing Values:\n", df.isnull().sum())
df.dropna(inplace=True)
print("\nDescriptive Statistics:\n", df.describe())
top_calories = df.sort_values(by='Calories', ascending=False).head(10)
sns.barplot(x='Calories', y='Item', data=top_calories, palette='Reds_r')
plt.title('Top 10 High-Calorie Items at McDonald’s')
plt.xlabel('Calories')
plt.ylabel('Menu Item')
plt.tight_layout()
plt.show()
sns.scatterplot(x='Total Fat (g)', y='Sodium (mg)', data=df, hue='Category', palette='deep')
plt.title('Fat vs Sodium by Category')
plt.xlabel('Total Fat (g)')
plt.ylabel('Sodium (mg)')
plt.tight_layout()
plt.show()
correlation = df.corr(numeric_only=True)
sns.heatmap(correlation, annot=True, cmap='coolwarm')
plt.title('Feature Correlation Heatmap')
plt.tight_layout()
plt.show()
print("\n Recommendations:")
print("- Reduce sodium in high-fat products to create healthier options.")
print("- Highlight low-calorie and balanced items in marketing materials.")
print("- Introduce portion control or custom meal builder tools for health-conscious consumers.")
